from config.ga_config import POPULATION_SIZE, LOWER_BOUND, UPPER_BOUND, GENERATION_COUNT, MUTATION_RATE,CROSSORATE_RATE ,TOURNAMENT_SIZE
from core.algorithm import genetic_algorithm

m1 , m2 =genetic_algorithm(POPULATION_SIZE,GENERATION_COUNT,LOWER_BOUND,UPPER_BOUND,MUTATION_RATE,CROSSORATE_RATE,TOURNAMENT_SIZE)

print(m1)
print(m2)

